project:
  type: book

book:
  title: "Cours d'organologie L2"
  author: "Matthieu Lainé"
  date: "2026"
  chapters:
    - index.qmd
    - intro.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



